### ISSUE TITLE
Home page corrections

### ISSUE THREAD

**Issue by shribalajiganesan** [chriscurly/ztapparel#1]
1. Replace the placeholder images with a image in the demo URL
2. Remove the black stripe in the home page
3. "MANUFACTURING & PRODUCTION" need to be replace with About us keep single line description about the zt apparels
4. "WHO WE ARE" replace this section with "Our Services" in the PDF, and "MANUFACTURING & PRODUCTION" from PDF
5. "WHAT WE DO?" need to be replaced with "Our Process"
6. Contact us link not working
7. Remove the latest news in the footer section
8. Remove my accounts in the footer
9. Remove total downloads
10. Copyrights need to be changed to zcodia technologies
11. Change the logo
12. Setup newsletter subscription

**Comment by chriscurly** [comment]
Completed @shribalajiganesan
